name: Player-Compass
version: 1.16.1
author: AnonymousRand
main: AnonymousRand.PlayerCompass.PlayerCompass
api-version: 1.16
commands:
  start:
    description: use /start [Target]
    usage: /start
    permission: yes